import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#4A6741", // กำหนดสีธีมของเบราว์เซอร์
  viewportFit: "cover", // กำหนดให้เว็บแสดงผลเต็มหน้าจอ รวมถึงส่วนที่มี notch หรือ rounded corners
  width: "device-width", // กำหนดความกว้างของเว็บให้เท่ากับความกว้างของอุปกรณ์
  initialScale: 1.0, // กำหนดระดับการซูมเริ่มต้นเป็น 100%
  maximumScale: 1, // จำกัดระดับการซูมสูงสุดไว้ที่ 100%
  userScalable: false, // ไม่อนุญาตให้ผู้ใช้ซูมหน้าเว็บ
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
